# Pandas Data Conversion

This notebook demonstrates different techniques for converting and transforming data using Pandas.

## Topics Covered

- Mapping values with `map()`
- Converting categorical data
- Using `factorize()`
- Converting continuous values
- Creating bins with `cut()`
- Creating quantile-based bins with `qcut()`
- Working with categorical representations

## Goal

The goal is to understand how to convert raw data into useful formats for analysis and machine learning.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_convert = pd.read_csv('../data/titanic.csv')
df_convert.head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [4]:
pd.DataFrame(df_convert['Sex']).head(5)

      Sex
0    male
1  female
2  female
3  female
4    male

In [5]:
df_convert['sex_num'] = df_convert['Sex'].map({'male' : 0 , 'female' : 1})

In [6]:
df_convert['sex_num']

0      0
1      1
2      1
3      1
4      0
      ..
882    0
883    1
884    1
885    0
886    0
Name: sex_num, Length: 887, dtype: int64

In [7]:
df_convert['sex_factorize'] = df_convert['Sex'].factorize()[0]

In [8]:
df_convert['sex_factorize']

0      0
1      1
2      1
3      1
4      0
      ..
882    0
883    1
884    1
885    0
886    0
Name: sex_factorize, Length: 887, dtype: int64

In [10]:
df_convert['Sex'].factorize()[1]

Index(['male', 'female'], dtype='object')

In [11]:
set(df_convert['Sex'])

{'female', 'male'}

In [14]:
df_convert.head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare,sex_num,sex_factorize
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,0,0
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,1,1
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,1,1
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,1,1
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,0,0

In [16]:
pd.DataFrame(pd.cut(df_convert['Age'] , bins=[0 , 18 , 25 , 99] , labels=['child' , 'young' , 'old']))

       Age
0    young
1      old
2      old
3      old
4      old
..     ...
882    old
883  young
884  child
885    old
886    old

[887 rows x 1 columns]

In [17]:
pd.qcut(df_convert['Age'] , q=3)

0      (0.419, 22.333]
1         (34.0, 80.0]
2       (22.333, 34.0]
3         (34.0, 80.0]
4         (34.0, 80.0]
            ...
882     (22.333, 34.0]
883    (0.419, 22.333]
884    (0.419, 22.333]
885     (22.333, 34.0]
886     (22.333, 34.0]
Name: Age, Length: 887, dtype: category
Categories (3, interval[float64, right]): [(0.419, 22.333] < (22.333, 34.0] < (34.0, 80.0]]

In [18]:
pd.qcut(df_convert['Age'] , q=3).value_counts()

Age
(22.333, 34.0]     307
(0.419, 22.333]    296
(34.0, 80.0]       284
Name: count, dtype: int64