# Renaming Columns in Pandas

This notebook demonstrates different approaches to renaming columns in a Pandas DataFrame.

## Topics Covered

- Renaming individual columns
- Renaming multiple columns
- Using `rename()`
- Working with column names
- Modifying DataFrame column labels

## Goal

The goal is to understand how to rename and organize DataFrame columns effectively.

In [3]:
import pandas as pd
import numpy as np

# Rename Columns

In [4]:
np.random.rand(5 , 2)

array([[0.6384102 , 0.85998689],
       [0.17340746, 0.09371211],
       [0.08261491, 0.12687634],
       [0.629495  , 0.07165546],
       [0.95798743, 0.7323    ]])

In [6]:
pd.DataFrame(np.random.rand(5 , 10))

,0,1,2,3,4,5,6,7,8,9
0,0.758783,0.508052,0.005380,0.702353,0.645979,0.685692,0.248748,0.219611,0.489874,0.983189
1,0.752060,0.618186,0.199239,0.108893,0.232062,0.644573,0.175509,0.119463,0.501070,0.424782
2,0.164615,0.864797,0.503805,0.385487,0.043167,0.448858,0.517768,0.611203,0.125673,0.561579
3,0.192884,0.041960,0.900357,0.654753,0.924884,0.131381,0.400252,0.328836,0.362885,0.740907
4,0.221509,0.544463,0.406616,0.340051,0.509087,0.947228,0.981913,0.894461,0.561544,0.448051

In [7]:
pd.DataFrame(np.random.rand(5 , 10) , columns=list('ABCDEFGHIJ'))

,A,B,C,D,E,F,G,H,I,J
0,0.376226,0.055815,0.063940,0.215080,0.313893,0.458064,0.264387,0.542967,0.693414,0.303523
1,0.944749,0.974622,0.965768,0.410704,0.396036,0.091260,0.208615,0.506592,0.541947,0.926677
2,0.420989,0.451335,0.969729,0.102348,0.633581,0.915533,0.677797,0.939827,0.916684,0.076137
3,0.157600,0.052574,0.693294,0.613353,0.043611,0.095100,0.092506,0.271350,0.723040,0.363040
4,0.979435,0.269509,0.170038,0.589920,0.568969,0.524393,0.798568,0.039812,0.217410,0.827974

In [11]:
B = pd.DataFrame({'column one' : [10 , 30] , 'column two' : [20 , 40]})
B

   column one  column two
0          10          20
1          30          40

In [12]:
B = B.rename({'column one' : 'test 1 ' , 'column two' : 'test 2 '} , axis='columns')
B

   test 1   test 2
0       10       20
1       30       40

In [15]:
B.columns = ['one_1' , 'two_2']
B

   one_1  two_2
0     10     20
1     30     40

In [16]:
B.columns = B.columns.str.replace('_' , '')

In [17]:
B

   one1  two2
0    10    20
1    30    40

In [18]:
B.add_prefix('_X_')

   _X_one1  _X_two2
0       10       20
1       30       40

In [19]:
B.add_suffix('_X_')

   one1_X_  two2_X_
0       10       20
1       30       40