# Comparing DataFrames and Series in Pandas

This notebook explores different methods for comparing Pandas DataFrames and Series.

## Topics Covered

- Comparing DataFrames
- Comparing Series
- Using `equals()`
- Comparing values
- Checking whether two DataFrames contain equivalent data

## Goal

The goal is to understand how to determine whether Pandas objects are equal or contain the same data.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# How to Check Equality

In [3]:
df = pd.DataFrame({'First' : [1,2,np.nan,3,4] , 'Second' : [1,2,np.nan,3,4]})

In [4]:
df

   First  Second
0    1.0     1.0
1    2.0     2.0
2    NaN     NaN
3    3.0     3.0
4    4.0     4.0

In [5]:
df.First == df.Second

0     True
1     True
2    False
3     True
4     True
dtype: bool

In [6]:
np.nan == np.nan

False

In [7]:
df.First.equals(df.Second)

True

In [8]:
df_new = df.copy()
df_new.equals(df)

True

In [13]:
df.isna()

   First  Second
0  False   False
1  False   False
2   True    True
3  False   False
4  False   False

In [16]:
df.isin([4]) # find number 4

   First  Second
0  False   False
1  False   False
2  False   False
3  False   False
4   True    True

In [18]:
df.value_counts()

First  Second
1.0    1.0       1
2.0    2.0       1
3.0    3.0       1
4.0    4.0       1
Name: count, dtype: int64

In [20]:
df.isnull().value_counts()

First  Second
False  False     4
True   True      1
Name: count, dtype: int64

In [32]:
df.isetitem(1 , 5)

In [33]:
df

  First  Second
0    00       5
1    00       5
2    00       5
3    00       5
4    00       5

In [34]:
df['First'] = '00'

In [35]:
df

  First  Second
0    00       5
1    00       5
2    00       5
3    00       5
4    00       5