# Filtering Data with Pandas Query

This notebook demonstrates how to use the Pandas `query()` method to filter and analyze DataFrame data.

## Topics Covered

- Filtering rows with `query()`
- Using comparison operators
- Combining conditions
- Querying string and numeric columns
- Using query results in data analysis

## Goal

The goal is to learn how `query()` can make DataFrame filtering more readable and expressive.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Query

In [3]:
df = pd.read_csv('../data/stocks.csv')
df

         Date   Close    Volume Symbol
0  2016-10-03   31.50  14070500   CSCO
1  2016-10-03  112.52  21701800   AAPL
2  2016-10-03   57.42  19189500   MSFT
3  2016-10-04  113.00  29736800   AAPL
4  2016-10-04   57.24  20085900   MSFT
5  2016-10-04   31.35  18460400   CSCO
6  2016-10-05   57.64  16726400   MSFT
7  2016-10-05   31.59  11808600   CSCO
8  2016-10-05  113.05  21453100   AAPL

In [6]:
df[df['Symbol'] == 'AAPL']

         Date   Close    Volume Symbol
1  2016-10-03  112.52  21701800   AAPL
3  2016-10-04  113.00  29736800   AAPL
8  2016-10-05  113.05  21453100   AAPL

In [7]:
df[df.Symbol == 'AAPL']

         Date   Close    Volume Symbol
1  2016-10-03  112.52  21701800   AAPL
3  2016-10-04  113.00  29736800   AAPL
8  2016-10-05  113.05  21453100   AAPL

In [9]:
df.query("Symbol == 'AAPL'")

         Date   Close    Volume Symbol
1  2016-10-03  112.52  21701800   AAPL
3  2016-10-04  113.00  29736800   AAPL
8  2016-10-05  113.05  21453100   AAPL

In [10]:
set(df['Symbol'])

{'AAPL', 'CSCO', 'MSFT'}

In [11]:
df['Symbol'].value_counts()

Symbol
CSCO    3
AAPL    3
MSFT    3
Name: count, dtype: int64

In [12]:
df.groupby('Volume').mean(numeric_only=True)

           Close
Volume
11808600   31.59
14070500   31.50
16726400   57.64
18460400   31.35
19189500   57.42
20085900   57.24
21453100  113.05
21701800  112.52
29736800  113.00

In [13]:
group = df.groupby('Symbol')

In [18]:
for symbol , data , in group:
    print(symbol)
    print(data)

AAPL
         Date   Close    Volume Symbol
1  2016-10-03  112.52  21701800   AAPL
3  2016-10-04  113.00  29736800   AAPL
8  2016-10-05  113.05  21453100   AAPL
CSCO
         Date  Close    Volume Symbol
0  2016-10-03  31.50  14070500   CSCO
5  2016-10-04  31.35  18460400   CSCO
7  2016-10-05  31.59  11808600   CSCO
MSFT
         Date  Close    Volume Symbol
2  2016-10-03  57.42  19189500   MSFT
4  2016-10-04  57.24  20085900   MSFT
6  2016-10-05  57.64  16726400   MSFT

In [19]:
df_groups = pd.concat([data for symbol , data in df.groupby('Symbol')])

In [20]:
df_groups

         Date   Close    Volume Symbol
1  2016-10-03  112.52  21701800   AAPL
3  2016-10-04  113.00  29736800   AAPL
8  2016-10-05  113.05  21453100   AAPL
0  2016-10-03   31.50  14070500   CSCO
5  2016-10-04   31.35  18460400   CSCO
7  2016-10-05   31.59  11808600   CSCO
2  2016-10-03   57.42  19189500   MSFT
4  2016-10-04   57.24  20085900   MSFT
6  2016-10-05   57.64  16726400   MSFT

In [21]:
df.groupby('Symbol')[['Close' , 'Volume']].mean()

             Close        Volume
Symbol
AAPL    112.856667  2.429723e+07
CSCO     31.480000  1.477983e+07
MSFT     57.433333  1.866727e+07

In [22]:
df.groupby('Symbol')[['Close']].mean()

             Close
Symbol
AAPL    112.856667
CSCO     31.480000
MSFT     57.433333

In [23]:
temp = df.groupby('Symbol')[['Close' , 'Volume']].mean()
temp[temp.Close < 100]

            Close        Volume
Symbol
CSCO    31.480000  1.477983e+07
MSFT    57.433333  1.866727e+07

In [24]:
df.groupby('Symbol')[['Close' , 'Volume']].mean().query('Close < 100')

            Close        Volume
Symbol
CSCO    31.480000  1.477983e+07
MSFT    57.433333  1.866727e+07