# Apply, Map and Custom Functions in Pandas

This notebook explores different ways to apply functions to Pandas Series and DataFrames.

## Topics Covered

- Using `apply()`
- Using `map()`
- Applying custom functions
- Applying functions to rows and columns
- Working with lambda functions
- Comparing different function application techniques

## Goal

The goal is to understand how custom functions can be applied efficiently to transform and process Pandas data.

In [23]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Apply, Map, Applymap

Map       → Series
Apply     → DataFrame
ApplyMap  → DataFrame

In [2]:
df = pd.read_csv('../data/employee.csv')
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [4]:
set(df['Department'])

{'Human Resources', 'Research & Development', 'Sales'}

In [7]:
df.index

RangeIndex(start=0, stop=1470, step=1)

In [9]:
df.shape

(1470, 35)

In [10]:
df[(df['Department'] == 'Sales') & (df['DailyRate'] > 1000)]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
18,53,No,Travel_Rarely,1219,Sales,2,4,Life Sciences,1,23,...,3,80,0,31,3,3,25,8,3,7
21,36,Yes,Travel_Rarely,1218,Sales,9,4,Life Sciences,1,27,...,2,80,0,10,4,3,5,3,0,3
39,33,No,Travel_Frequently,1141,Sales,1,3,Life Sciences,1,52,...,1,80,2,10,3,3,5,3,1,3
46,34,No,Non-Travel,1065,Sales,23,4,Marketing,1,60,...,3,80,0,10,2,3,9,5,8,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1417,31,No,Travel_Rarely,1154,Sales,2,2,Life Sciences,1,1996,...,3,80,1,3,1,3,2,2,1,2
1433,25,No,Travel_Rarely,1382,Sales,8,2,Other,1,2018,...,2,80,1,6,3,2,5,3,0,4
1453,36,No,Travel_Rarely,1120,Sales,11,4,Marketing,1,2045,...,1,80,1,8,2,2,6,3,0,0
1464,26,No,Travel_Rarely,1167,Sales,5,3,Other,1,2060,...,4,80,0,5,2,3,4,2,0,0
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8

In [19]:
df['DailyRate']

0       110.2
1        27.9
2       137.3
3       139.2
4        59.1
        ...
1465     88.4
1466     61.3
1467     15.5
1468    102.3
1469     62.8
Name: DailyRate, Length: 1470, dtype: float64

In [20]:
def functions(x):
    return x/10

df['DailyRate'] = df['DailyRate'].map(functions)
df['DailyRate']

0       11.02
1        2.79
2       13.73
3       13.92
4        5.91
        ...
1465     8.84
1466     6.13
1467     1.55
1468    10.23
1469     6.28
Name: DailyRate, Length: 1470, dtype: float64

# Apply Method

In [21]:
df[['DailyRate' , 'MonthlyRate']].apply(functions)

      DailyRate  MonthlyRate
0         1.102       1947.9
1         0.279       2490.7
2         1.373        239.6
3         1.392       2315.9
4         0.591       1663.2
...         ...          ...
1465      0.884       1229.0
1466      0.613       2145.7
1467      0.155        517.4
1468      1.023       1324.3
1469      0.628       1022.8

[1470 rows x 2 columns]

# ApplyMap

In [24]:
df[['DailyRate' , 'MonthlyRate']].applymap(functions)

      DailyRate  MonthlyRate
0         1.102       1947.9
1         0.279       2490.7
2         1.373        239.6
3         1.392       2315.9
4         0.591       1663.2
...         ...          ...
1465      0.884       1229.0
1466      0.613       2145.7
1467      0.155        517.4
1468      1.023       1324.3
1469      0.628       1022.8

[1470 rows x 2 columns]