# Numeric Data Conversion in Pandas

This notebook demonstrates different techniques for converting data into numeric types.

## Topics Covered

- Converting values with `astype()`
- Using `pd.to_numeric()`
- Handling invalid numeric values
- Working with numeric and non-numeric data
- Comparing different conversion approaches

## Goal

The goal is to understand how to safely convert data into numeric formats for analysis and further processing.

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({'Column_one':['1.1', '2.2', '3.3'],
                   'Column_two':['4.4', '5.5', '6.6'],
                   'Column_three':['7.7', '8.8', '-']})
df

  Column_one Column_two Column_three
0        1.1        4.4          7.7
1        2.2        5.5          8.8
2        3.3        6.6            -

In [4]:
df.dtypes

Column_one      object
Column_two      object
Column_three    object
dtype: object

In [5]:
convert = df.astype({'Column_one' : 'float' , 'Column_two' : 'float'}).dtypes
convert

Column_one      float64
Column_two      float64
Column_three     object
dtype: object

In [6]:
convert = df.astype({'Column_one' : 'float' , 'Column_two' : 'float'})
convert

   Column_one  Column_two Column_three
0         1.1         4.4          7.7
1         2.2         5.5          8.8
2         3.3         6.6            -

In [7]:
df['Column_three'] = pd.to_numeric(df['Column_three'], errors='coerce')
print(df)

  Column_one Column_two  Column_three
0        1.1        4.4           7.7
1        2.2        5.5           8.8
2        3.3        6.6           NaN

In [8]:
df.dtypes

Column_one       object
Column_two       object
Column_three    float64
dtype: object

In [9]:
df['Column_three'] = pd.to_numeric(df.Column_three , errors='coerce').fillna(0)

In [10]:
df

  Column_one Column_two  Column_three
0        1.1        4.4           7.7
1        2.2        5.5           8.8
2        3.3        6.6           0.0

### Alternative Solution

In [12]:
df = df.apply(pd.to_numeric , errors='coerce').fillna(0)

In [13]:
df

   Column_one  Column_two  Column_three
0         1.1         4.4           7.7
1         2.2         5.5           8.8
2         3.3         6.6           0.0

In [14]:
df.dtypes

Column_one      float64
Column_two      float64
Column_three    float64
dtype: object