# Date and Time Operations in Pandas

This notebook explores Pandas tools for creating, converting, and working with date and time data.

## Topics Covered

- Creating date ranges with `date_range()`
- Converting values to datetime
- Working with datetime columns
- Extracting date and time components
- Performing date-based operations
- Working with Jalali dates

## Goal

The goal is to understand how Pandas handles temporal data and how datetime information can be used in data analysis.

In [4]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.date_range(start='2022-11-15' , end='2022-11-21')

DatetimeIndex(['2022-11-15', '2022-11-16', '2022-11-17', '2022-11-18',
               '2022-11-19', '2022-11-20', '2022-11-21'],
              dtype='datetime64[ns]', freq='D')

In [5]:
pd.date_range(start='2023-01-01 00:00:00' , end='2023-01-01 00:24:00' , freq='6T')

DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 00:06:00',
               '2023-01-01 00:12:00', '2023-01-01 00:18:00',
               '2023-01-01 00:24:00'],
              dtype='datetime64[ns]', freq='6min')

In [6]:
pd.date_range(start='2023-01-01 00:00:00' , end='2023-03-01 00:24:00' , freq='W')

DatetimeIndex(['2023-01-01', '2023-01-08', '2023-01-15', '2023-01-22',
               '2023-01-29', '2023-02-05', '2023-02-12', '2023-02-19',
               '2023-02-26'],
              dtype='datetime64[ns]', freq='W-SUN')

In [7]:
pd.date_range(start='2023-01-01 00:00:00' , end='2023-01-01 00:24:00' , periods=10)

DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 00:02:40',
               '2023-01-01 00:05:20', '2023-01-01 00:08:00',
               '2023-01-01 00:10:40', '2023-01-01 00:13:20',
               '2023-01-01 00:16:00', '2023-01-01 00:18:40',
               '2023-01-01 00:21:20', '2023-01-01 00:24:00'],
              dtype='datetime64[ns]', freq=None)

In [8]:
pd.date_range(start='2023-01-01' , end='2023-12-01' , freq='Q')

DatetimeIndex(['2023-03-31', '2023-06-30', '2023-09-30'], dtype='datetime64[ns]', freq='QE-DEC')

In [9]:
pd.date_range(start='2023-01-01 00:00:00' , end='2024-12-01 00:24:00' , freq='5ME')

DatetimeIndex(['2023-01-31', '2023-06-30', '2023-11-30', '2024-04-30',
               '2024-09-30'],
              dtype='datetime64[ns]', freq='5ME')

In [10]:
pd.date_range(start='2023-01-01 00:00:00' , end='2024-12-01 00:24:00' , freq='5M')

DatetimeIndex(['2023-01-31', '2023-06-30', '2023-11-30', '2024-04-30',
               '2024-09-30'],
              dtype='datetime64[ns]', freq='5ME')

# DateTime in Pandas

In [11]:
date_sr =pd.Series(pd.date_range('2022-11-15' , periods=3 , freq='D'))
date_sr

0   2022-11-15
1   2022-11-16
2   2022-11-17
dtype: datetime64[ns]

In [12]:
list = ['Day1','Day2','Day3']

date_sr.index = list

In [13]:
date_sr

Day1   2022-11-15
Day2   2022-11-16
Day3   2022-11-17
dtype: datetime64[ns]

In [14]:
change_format = date_sr.dt.strftime('%d,%m,%Y') 
print(change_format)

Day1    15,11,2022
Day2    16,11,2022
Day3    17,11,2022
dtype: object

In [15]:
date_sr = pd.to_datetime(pd.Series('2022-11-15'))
date_sr

0   2022-11-15
dtype: datetime64[ns]

In [16]:
change_format = date_sr.dt.strftime('%d/%m/%Y')
print(change_format)

0    15/11/2022
dtype: object

In [17]:
df = pd.DataFrame({'date': ['3/10/2022', '3/11/2022', '3/12/2022'],
                   'value': [100, 200, 300]})
df['date'] = pd.to_datetime(df['date'])
df

        date  value
0 2022-03-10    100
1 2022-03-11    200
2 2022-03-12    300

In [18]:
df = pd.DataFrame({'date': ['3/10/2022', '3/11/2022', '3/12/2022'],
                   'value': [100, 200, 300]})

df['date'] = pd.to_datetime(df['date'], dayfirst=True)
df

        date  value
0 2022-10-03    100
1 2022-11-03    200
2 2022-12-03    300

In [19]:
df = pd.DataFrame({'date': ['2022-6-10 20:30:0', 
                            '2022-7-1 19:45:30', 
                            '2022-10-12 4:5:1'],
                   'value': [100, 200, 300]})
df['date'] = pd.to_datetime(df['date'], format="%Y-%d-%m %H:%M:%S")
df

                 date  value
0 2022-10-06 20:30:00    100
1 2022-01-07 19:45:30    200
2 2022-12-10 04:05:01    300

In [20]:
df = pd.DataFrame({'year': [2022, 2023],
                   'month': [2, 3],
                   'day': [4, 5]})
df['date'] = pd.to_datetime(df)
df

   year  month  day       date
0  2022      2    4 2022-02-04
1  2023      3    5 2023-03-05

In [21]:
df = pd.DataFrame({'name': ['Soheil', 'Mahtab', 'Baran'],
                 'DoB': ['10-09-1989', '06-28-2020', '06-28-2022']})
df['DoB'] = pd.to_datetime(df['DoB'])

In [22]:
df['year']= df['DoB'].dt.year
df['month']= df['DoB'].dt.month
df['day']= df['DoB'].dt.day
df

     name        DoB  year  month  day
0  Soheil 1989-10-09  1989     10    9
1  Mahtab 2020-06-28  2020      6   28
2   Baran 2022-06-28  2022      6   28

In [23]:
dw_mapping={
    0: 'Saturday',
    1: 'Sunday',
    2: 'Monday', 
    3: 'Tuesday', 
    4: 'Wednesday', 
    5: 'Thursday', 
    6: 'Friday'
} 
df['day_of_week_name']=df['DoB'].dt.weekday.map(dw_mapping)
df

     name        DoB  year  month  day day_of_week_name
0  Soheil 1989-10-09  1989     10    9         Saturday
1  Mahtab 2020-06-28  2020      6   28           Friday
2   Baran 2022-06-28  2022      6   28           Sunday

In [24]:
dw_mapping={
    0: 'شنبه',
    1: 'یکشنبه',
    2: 'دوشنبه', 
    3: 'سه شنبه', 
    4: 'چهارشنبه', 
    5: 'پنجشنبه', 
    6: 'جمعه',
} 
df['روز هفته']=df['DoB'].dt.weekday.map(dw_mapping)
df

     name        DoB  year  month  day day_of_week_name روز هفته
0  Soheil 1989-10-09  1989     10    9         Saturday     شنبه
1  Mahtab 2020-06-28  2020      6   28           Friday     جمعه
2   Baran 2022-06-28  2022      6   28           Sunday   یکشنبه