# Ordered Categorical Data in Pandas

This notebook demonstrates how Pandas categorical data can be used to represent values with a meaningful order.

## Topics Covered

- Creating categorical data
- Understanding categorical variables
- Defining category order
- Using `CategoricalDtype`
- Sorting ordered categorical values
- Working with ordered categories

## Goal

The goal is to understand how ordered categorical data can represent meaningful relationships between categories.

In [2]:
import pandas as pd
from pandas.api.types import CategoricalDtype

In [3]:
d = {"ID":[100,200,300,400] , "quality":["bad","very good","good","execllent"]}
df = pd.DataFrame(d)
df

    ID    quality
0  100        bad
1  200  very good
2  300       good
3  400  execllent

In [4]:
df = df.sort_values("quality" , ascending=True)
df

    ID    quality
0  100        bad
3  400  execllent
2  300       good
1  200  very good

In [5]:
df[df["quality"] > "bad"]

    ID    quality
3  400  execllent
2  300       good
1  200  very good